[package]
name = "cubiomes-sys"
version = "0.1.0"
edition = "2024"

[dependencies]



[build-dependencies]
bindgen = { version = "0.72.1", features = ["runtime", "logging", "prettyplease"], default-features = false }
cc = "1.2.43"
cmake = "0.1.54"

[dev-dependencies]
rstest = "0.26.1"
